parameters:
    user_password: '%env(string:USER_PASSWORD)%'

security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '%user_password%', roles: ['ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Monitor Backup
    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
